FORMAT: 1A
HOST: https://swe-endangered-animals.appspot.com

# Endangered Animals

## Common name of Animal [/get_common_name_of_animal/]

### GET: /get_common_name_of_animal/?sci_name [GET]

Given a scientific name, retrieves the common name for an animal..
    
Example: Let's say you want to find the common name for the animal "Accipiter gentilis"
    
**HTTP Request:**
`https://swe-endangered-animals.appspot.com/get_common_name_of_animal/?sci_name=Accipiter gentilis`

+ Response 200 (application/json)

    + Body
    
            {
                "common_name": "Northern Goshawk"
            }
            
## Animal [/single_animal_data/]

### GET: /single_animal_data/?animal_name [GET]

Retrieves data for an animal: common name, scientific name, image, video, vulnerability, conservation measures, citation link, associated habitats/threats/countries.
    
Example: Let's say you want to find data on "Semi-collared Hawk"
    
**HTTP Request:**
`https://swe-endangered-animals.appspot.com/single_animal_data?animal_name=Semi-collared Hawk`

+ Response 200 (application/json)

    + Body
    
            {
                "common_name": "Semi-collared Hawk",
                "scientific_name": "Accipiter collaris",
                "vulnerability_status":"vulnerable",
                "citation":"Campbell, J. 2007. Abronia oaxacae. The IUCN Red List of Threatened Species 2007: e.T63685A12697055. http://dx.doi.org/10.2305/IUCN.UK.2007.RLTS.T63685A12697055.en",
                "conservation_measure": "Resource & habitat protection",
                "video_url": "https://www.youtube.com/watch?v=vy2RKH2v5_E",
                "imageLink": "http://www.planetofbirds.com/Master/ACCIPITRIFORMES/Accipitridae/pics/Nicobar%20Sparrowhawk.jpg",
                "web_link": "http://apiv3.iucnredlist.org/api/v3/website/Accipiter collaris",
                "assoc_habitats":[
                    "Forest - Subtropical/Tropical Moist Montane"
                ],
                "assoc_threats":[
                    "Annual & perennial non-timber crops",
                    "Agro-industry farming",
                    "Livestock farming & ranching",
                    "Agro-industry grazing, ranching or farming",
                    "Work & other activities"
                ],
                "assoc_countries": [
                    "Colombia",
                    "Ecuador",
                    "Peru",
                    "Venezuela, Bolivarian Republic of"
                ]
            }
            
## All Animals [/all_animal_data]

### GET: /all_animal_data [GET]

Retrieves data for all animals.

This endpoint basically calls /single_animal_data on each animal.

**HTTP Request:**
`https://swe-endangered-animals.appspot.com/all_animal_data`

+ Response 200 (application/json)

    + Body
    
            [
                {
                    "common_name": "Semi-collared Hawk",
                    "scientific_name": "Accipiter collaris",
                    "vulnerability_status":"vulnerable",
                    "citation":"Campbell, J. 2007. Abronia oaxacae. The IUCN Red List of Threatened Species 2007: e.T63685A12697055. http://dx.doi.org/10.2305/IUCN.UK.2007.RLTS.T63685A12697055.en",
                    "conservation_measure": "Resource & habitat protection",
                    "video_url": "https://www.youtube.com/watch?v=vy2RKH2v5_E",
                    "imageLink": "http://www.planetofbirds.com/Master/ACCIPITRIFORMES/Accipitridae/pics/Nicobar%20Sparrowhawk.jpg",
                    "web_link": "http://apiv3.iucnredlist.org/api/v3/website/Accipiter collaris",
                    "assoc_habitats":[
                        "Forest - Subtropical/Tropical Moist Montane"
                    ],
                    "assoc_threats":[
                        "Annual & perennial non-timber crops",
                        "Agro-industry farming",
                        "Livestock farming & ranching",
                        "Agro-industry grazing, ranching or farming",
                        "Work & other activities"
                    ],
                    "assoc_countries": [
                        "Colombia",
                        "Ecuador",
                        "Peru",
                        "Venezuela, Bolivarian Republic of"
                    ]
                },
                {
                    "common_name": "Reid's Arboreal Alligator Lizard",
                    "scientific_name": "Abronia reidi",
                    "vulnerability_status":"Data Deficient",
                    "citation":"Flores-Villela, O. & Lopez-Luna, M.A. 2007. Abronia reidi. The IUCN Red List of Threatened Species 2007: e.T63689A12697921. http://dx.doi.org/10.2305/IUCN.UK.2007.RLTS.T63689A12697921.en",
                    "conservation_measure": "Site/area management",
                    "video_url": "https://www.youtube.com/watch?v=cUgHxoI3mFk",
                    "imageLink": "http://www.adrianpetch.com/Absmith.jpeg",
                    "web_link": "http://apiv3.iucnredlist.org/api/v3/website/Abronia reidi",
                    "assoc_habitats":[
                        "Forest - Subtropical/Tropical Moist Montane"
                    ],
                    "assoc_threats":[
                        "Annual & perennial non-timber crops",
                        "Small-holder farming",
                        "Logging & wood harvesting",
                        "Motivation Unknown/Unrecorded"
                    ],
                    "assoc_countries": [
                        "Mexico"
                    ]
                }
            ]

## Threat [/single_threat_data/]

### GET: /single_threat_data/?threat_name   [GET]

Retrieves data for a specific threat: name, image, timing, severity, associated animals/habitats.

Example: Let's say you want to find data on "Agro-industry farming"
    
**HTTP Request:**
`https://swe-endangered-animals.appspot.com/single_threat_data?threat_name=Agro-industry farming`

+ Response 200 (application/json)

    + Body
    
               {
                    "name": "Agro-industry farming",
                    "image": "https://vermont4evolution.files.wordpress.com/2011/07/mono1.jpg",
                    "timing": "ongoing",
                    "severity": "4.5",
                    "assoc_animals": [
                        "Accipiter butleri",
                        "Accipiter butleri",
                        "Ablepharus bivittatus",
                        "Accipiter collaris",
                        "Abronia oaxacae",
                        "Acanthochelys pallidipectoris",
                        "Acanthosaura lepidogaster",
                        "Abronia graminea",
                        "Ablepharus deserti",
                        "Acanthodactylus beershebensis",
                        "Aburria aburri",
                        "Acantopsis octoactinotos"
                    ],
                    "assoc_habitats": [
                        "Wetlands (inland) - Shrub Dominated Wetlands",
                        "Wetlands (inland) - Permanent Rivers/Streams/Creeks (includes waterfalls)",
                        "Forest - Temperate",
                        "Grassland - Temperate",
                        "Forest - Subtropical/Tropical Moist Lowland",
                        "Desert - Temperate",
                        "Artificial/Aquatic - Ponds (below 8ha)",
                        "Shrubland - Subtropical/Tropical Dry",
                        "Artificial/Terrestrial - Rural Gardens",
                        "Wetlands (inland) - Seasonal/Intermittent Freshwater Marshes/Pools (under 8ha)",
                        "Forest - Subtropical/Tropical Moist Montane",
                        "Artificial/Terrestrial - Subtropical/Tropical Heavily Degraded Former Forest",
                        "Wetlands (inland) - Freshwater Springs and Oases",
                        "Artificial/Terrestrial - Plantations",
                        "Shrubland - Temperate",
                        "Grassland - Subtropical/Tropical Seasonally Wet/Flooded"
                    ]
                }

## All Threats [/all_threat_data]

### GET: /all_threat_data [GET]

Retrieves data for all threats.

This endpoint basically calls /single_threat_data on each threat.

**HTTP Request:**
`https://swe-endangered-animals.appspot.com/all_threat_data`
    
+ Response 200 (application/json)

    + Body
    

            [
               {
                    "name": "Agro-industry farming",
                    "image": "https://vermont4evolution.files.wordpress.com/2011/07/mono1.jpg",
                    "timing": "ongoing",
                    "severity": "4.5",
                    "assoc_animals": [
                        "Accipiter butleri",
                        "Accipiter butleri",
                        "Ablepharus bivittatus",
                        "Accipiter collaris",
                        "Abronia oaxacae",
                        "Acanthochelys pallidipectoris",
                        "Acanthosaura lepidogaster",
                        "Abronia graminea",
                        "Ablepharus deserti",
                        "Acanthodactylus beershebensis",
                        "Aburria aburri",
                        "Acantopsis octoactinotos"
                    ],
                    "assoc_habitats": [
                        "Wetlands (inland) - Shrub Dominated Wetlands",
                        "Wetlands (inland) - Permanent Rivers/Streams/Creeks (includes waterfalls)",
                        "Forest - Temperate",
                        "Grassland - Temperate",
                        "Forest - Subtropical/Tropical Moist Lowland",
                        "Desert - Temperate",
                        "Artificial/Aquatic - Ponds (below 8ha)",
                        "Shrubland - Subtropical/Tropical Dry",
                        "Artificial/Terrestrial - Rural Gardens",
                        "Wetlands (inland) - Seasonal/Intermittent Freshwater Marshes/Pools (under 8ha)",
                        "Forest - Subtropical/Tropical Moist Montane",
                        "Artificial/Terrestrial - Subtropical/Tropical Heavily Degraded Former Forest",
                        "Wetlands (inland) - Freshwater Springs and Oases",
                        "Artificial/Terrestrial - Plantations",
                        "Shrubland - Temperate",
                        "Grassland - Subtropical/Tropical Seasonally Wet/Flooded"
                    ]
                },
                {
                    "name": "Problematic native species/diseases",
                    "image": "http://www.gardeningknowhow.com/wp-content/uploads/2014/12/insv.jpg",
                    "timing": "ongoing",
                    "severity": "4.5",
                    "assoc_animals": [
                        "Acanthodactylus blanci",
                        "Acanthochelys pallidipectoris",
                        "Acanthodactylus beershebensis"
                    ],
                    "assoc_habitats": [
                        "Wetlands (inland) - Shrub Dominated Wetlands",
                        "Forest - Temperate",
                        "Artificial/Aquatic - Ponds (below 8ha)",
                        "Shrubland - Subtropical/Tropical Dry",
                        "Wetlands (inland) - Seasonal/Intermittent Freshwater Marshes/Pools (under 8ha)",
                        "Artificial/Terrestrial - Plantations",
                        "Shrubland - Mediterranean-type Shrubby Vegetation",
                        "Marine Coastal/Supratidal - Coastal Sand Dunes",
                        "Grassland - Subtropical/Tropical Seasonally Wet/Flooded"
                    ]
                }
            ]

## Habitat [/single_habitat_data/]

### GET: /single_habitat_data/?habitat_name [GET]

Retrieves data for a given habitat: name, image, suitability, associated animals/threats.

Example: Let's say you want to find data on the habitat "Artificial/Aquatic - Ponds (below 8ha)"
    
**HTTP Request:**
`https://swe-endangered-animals.appspot.com/single_habitat_data/?habitat_name=Artificial/Aquatic - Ponds (below 8ha)`

+ Response 200 (application/json)

    + Body
    
            {
                "name": "Artificial/Aquatic - Ponds (below 8ha)",
                "image": "http://thumb1.shutterstock.com/display_pic_with_logo/1771478/323878760/stock-photo-small-artificial-decorative-pond-with-rocks-and-plants-on-the-backyard-in-summer-323878760.jpg",
                "suitability": "Suitable",
                "assoc_animals": [
                    "Acanthochelys pallidipectoris"
                ],
                "assoc_countries": [
                    "Paraguay",
                    "Argentina",
                    "Bolivia, Plurinational States of"
                ]
            }

## All Habitats [/all_habitat_data]

### GET: /all_habitat_data [GET]

Retrieves data for all habitats.

This endpoint basically calls /single_habitat_data on each habitat.

**HTTP Request:**
`https://swe-endangered-animals.appspot.com/all_habitat_data`

+ Response 200 (application/json)

    + Body
    
            [
                {
                    "name": "Artificial/Aquatic - Ponds (below 8ha)",
                    "image": "http://thumb1.shutterstock.com/display_pic_with_logo/1771478/323878760/stock-photo-small-artificial-decorative-pond-with-rocks-and-plants-on-the-backyard-in-summer-323878760.jpg",
                    "suitability": "Suitable",
                    "assoc_animals": [
                        "Acanthochelys pallidipectoris"
                    ],
                    "assoc_countries": [
                        "Paraguay",
                        "Argentina",
                        "Bolivia, Plurinational States of"
                    ]
                },
                {
                    "name": "Wetlands (inland) - Permanent Freshwater Lakes (over 8ha)",
                    "image": "http://people.deu.edu.tr/melis.somay/resimler/swamps.jpg",
                    "suitability": "Suitable",
                    "assoc_animals": [
                        "Acanthobrama lissneri",
                        "Acanthobrama microlepis",
                        "Acanthobrama centisquama",
                        "Acanthobrama tricolor"
                    ],
                    "assoc_countries": [
                        "Turkey",
                        "Israel",
                        "Georgia",
                        "Iran, Islamic Republic of",
                        "Azerbaijan",
                        "Syrian Arab Republic",
                        "Jordan",
                        "Armenia",
                        "Palestinian Territory, Occupied"
                    ]
                }
            ]

## Country [/single_country_data/]

### GET: /single_country_data/?country_name [GET]

Retrieves data for a specific country: name, flag, coordinates, associated animals/habitats.

Example: Let's say you want to find data on "Azerbaijan"
    
**HTTP Request:**
`https://swe-endangered-animals.appspot.com/single_country_data/?country_name=Azerbaijan`

+ Response 200 (application/json)

    + Body
    
            {
                "name": "Azerbaijan",
                "flag": "http://cdn.wonderfulengineering.com/wp-content/uploads/2015/07/azerbaijan-flag-13.png",
                "coordinate": "lat: 40.143105 lng: 47.576927",
                "assoc_animals": [
                    "Ablepharus bivittatus",
                    "Accipiter badius",
                    "Acanthobrama microlepis",
                    "Accipiter gentilis",
                    "Acanthis flammea",
                    "Accipiter brevipes"
                ],
                "assoc_habitats": [
                    "Forest - Boreal",
                    "Artificial/Terrestrial - Urban Areas",
                    "Wetlands (inland) - Permanent Rivers/Streams/Creeks (includes waterfalls)",
                    "Savanna - Dry",
                    "Forest - Temperate",
                    "Grassland - Temperate",
                    "Forest - Subtropical/Tropical Moist Lowland",
                    "Shrubland - Subtropical/Tropical Dry",
                    "Artificial/Terrestrial - Rural Gardens",
                    "Wetlands (inland) - Permanent Freshwater Marshes/Pools (under 8ha)",
                    "Grassland - Subtropical/Tropical Dry",
                    "Artificial/Terrestrial - Plantations",
                    "Shrubland - Mediterranean-type Shrubby Vegetation",
                    "Wetlands (inland) - Permanent Freshwater Lakes (over 8ha)",
                    "Grassland - Tundra",
                    "Shrubland - Temperate"
                ]
            }

## All Countries [/all_country_data]

### GET: /all_country_data [GET]

Retrieves data for all countries.
    
This endpoint basically calls /single_country_data on each country.

**HTTP Request:**
`https://swe-endangered-animals.appspot.com/all_country_data`

+ Response 200 (application/json)

    + Body
    
            [
                {
                    "name": "Azerbaijan",
                    "flag": "http://cdn.wonderfulengineering.com/wp-content/uploads/2015/07/azerbaijan-flag-13.png",
                    "coordinate": "lat: 40.143105 lng: 47.576927",
                    "assoc_animals": [
                        "Ablepharus bivittatus",
                        "Accipiter badius",
                        "Acanthobrama microlepis",
                        "Accipiter gentilis",
                        "Acanthis flammea",
                        "Accipiter brevipes"
                    ],
                    "assoc_habitats": [
                        "Forest - Boreal",
                        "Artificial/Terrestrial - Urban Areas",
                        "Wetlands (inland) - Permanent Rivers/Streams/Creeks (includes waterfalls)",
                        "Savanna - Dry",
                        "Forest - Temperate",
                        "Grassland - Temperate",
                        "Forest - Subtropical/Tropical Moist Lowland",
                        "Shrubland - Subtropical/Tropical Dry",
                        "Artificial/Terrestrial - Rural Gardens",
                        "Wetlands (inland) - Permanent Freshwater Marshes/Pools (under 8ha)",
                        "Grassland - Subtropical/Tropical Dry",
                        "Artificial/Terrestrial - Plantations",
                        "Shrubland - Mediterranean-type Shrubby Vegetation",
                        "Wetlands (inland) - Permanent Freshwater Lakes (over 8ha)",
                        "Grassland - Tundra",
                        "Shrubland - Temperate"
                    ]
                },
                {
                    "name": "Bhutan",
                    "flag": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Flag_of_Bhutan.svg/2000px-Flag_of_Bhutan.svg.png",
                    "coordinate": "lat: 27.514162 lng: 90.433601",
                    "assoc_animals": [
                        "Acanthocobitis botia",
                        "Accipiter badius",
                        "Accipiter gentilis"
                    ],
                    "assoc_habitats": [
                        "Forest - Boreal",
                        "Artificial/Terrestrial - Urban Areas",
                        "Wetlands (inland) - Permanent Rivers/Streams/Creeks (includes waterfalls)",
                        "Savanna - Dry",
                        "Forest - Temperate",
                        "Grassland - Temperate",
                        "Forest - Subtropical/Tropical Moist Lowland",
                        "Shrubland - Subtropical/Tropical Dry",
                        "Artificial/Terrestrial - Rural Gardens",
                        "Grassland - Subtropical/Tropical Dry",
                        "Artificial/Terrestrial - Plantations",
                        "Grassland - Tundra"
                    ]
                }
            ]
