FORMAT: 1A
HOST: swe-endangered-animals.appspot.com

# Endangered Animals

## Animal [/single_animal_data/{animal_name}]

### GET: /single_animal_data/ANIMAL [GET]

Retrieves data for an animal: common name, scientific name, image, video, vulnerability, conservation measures, citation link, associated habitats/threats/countries.
    
Example: Let's say you want to find data on "African Elephant."
    
**HTTP Request:**
`https://swe-endangered-animals.appspot.com/single_animal_data/African Elephant`

+ Response 200 (application/json)

    + Body
    
            {
                "common_name": "African Elephant",
                "scientific_name": "Loxodonta africana",
                "vulnerability_status":"vulnerable",
                "citation":"Blanc, J. 2008. Loxodonta africana. The IUCN Red List of Threatened Species 2008: e.T12392A3339343. http://dx.doi.org/10.2305/IUCN.UK.2008.RLTS.T12392A3339343.en",
                "conservation_measure": "Resource & habitat protection",
                "video_url": "https://www.youtube.com/watch?v=kcGX_7n_JXY",
                "imageLink": "https://iucnredlist-photos.s3.amazonaws.com/thumb/1315258020.jpg?AWSAccessKeyId=AKIAJIJQNN2N2SMHLZJA&Expires=1536230105&Signature=Hcr7ZZv9PwtYvWSkOjgdZR2tJTc%3D",
                "web_link": "http://apiv3.iucnredlist.org/api/v3/website/Abudefduf vaigiensis",
                "assoc_habitats":[
                    "Desert - Hot",
                    "Desert - Temperate"
                ],
                "assoc_threats":[
                    "Housing and Urban Areas",
                    "Commercial and industrial areas"
                ],
                "assoc_countries": [
                    "Botswana",
                    "Burundi"
                ]
            }
            
## All Animals [/all_animal_data]

### GET: /all_animal_data/ [GET]

Retrieves data for all animals.

This endpoint basically calls /single_animal_data on each animal.

**HTTP Request:**
`https://swe-endangered-animals.appspot.com/single_animal_data/African Elephant`

+ Response 200 (application/json)

    + Body
    
            [
                {
                    "common_name": "African Elephant",
                    "scientific_name": "Loxodonta africana",
                    "vulnerability_status":"vulnerable",
                    "citation":"Blanc, J. 2008. Loxodonta africana. The IUCN Red List of Threatened Species 2008: e.T12392A3339343. http://dx.doi.org/10.2305/IUCN.UK.2008.RLTS.T12392A3339343.en",
                    "conservation_measure": "Resource & habitat protection",
                    "video_url": "https://www.youtube.com/watch?v=kcGX_7n_JXY",
                    "imageLink": "https://iucnredlist-photos.s3.amazonaws.com/thumb/1315258020.jpg?AWSAccessKeyId=AKIAJIJQNN2N2SMHLZJA&Expires=1536230105&Signature=Hcr7ZZv9PwtYvWSkOjgdZR2tJTc%3D",
                    "web_link": "http://apiv3.iucnredlist.org/api/v3/website/Abudefduf vaigiensis",
                    "assoc_habitats":[
                        "Desert - Hot",
                        "Desert - Temperate"
                    ],
                    "assoc_threats":[
                        "Housing and Urban Areas",
                        "Commercial and industrial areas"
                    ],
                    "assoc_countries": [
                        "Botswana",
                        "Burundi"
                    ]
                },
                {
                    "common_name": "African Elephant",
                    "scientific_name": "Loxodonta africana",
                    "vulnerability_status":"vulnerable",
                    "citation":"Blanc, J. 2008. Loxodonta africana. The IUCN Red List of Threatened Species 2008: e.T12392A3339343. http://dx.doi.org/10.2305/IUCN.UK.2008.RLTS.T12392A3339343.en",
                    "conservation_measure": "Resource & habitat protection",
                    "video_url": "https://www.youtube.com/watch?v=kcGX_7n_JXY",
                    "imageLink": "https://iucnredlist-photos.s3.amazonaws.com/thumb/1315258020.jpg?AWSAccessKeyId=AKIAJIJQNN2N2SMHLZJA&Expires=1536230105&Signature=Hcr7ZZv9PwtYvWSkOjgdZR2tJTc%3D",
                    "web_link": "http://apiv3.iucnredlist.org/api/v3/website/Abudefduf vaigiensis",
                    "assoc_habitats":[
                        "Desert - Hot",
                        "Desert - Temperate"
                    ],
                    "assoc_threats":[
                        "Housing and Urban Areas",
                        "Commercial and industrial areas"
                    ],
                    "assoc_countries": [
                        "Botswana",
                        "Burundi"
                    ]
                }
                ...
            ]

## Threat [/single_threat_data/{threat_name}]

### GET: /single_threat_data/THREAT   [GET]

Retrieves data for a specific threat: name, image, timing, severity, associated animals/habitats.

Example: Let's say you want to find data on "Agro-industry farming."
    
**HTTP Request:**
`https://swe-endangered-animals.appspot.com/single_threat_data/Agro-industry farming`

+ Response 200 (application/json)

    + Body
    
            {
                "name": "Agro-industry farming",
                "timing": "ongoing",
                "severity":"3.57",
                "image":"https://iucnredlist-photos.s3.amazonaws.com/thumb/1315258020.jpg?AWSAccessKeyId=AKIAJIJQNN2N2SMHLZJA&Expires=1536230105&Signature=Hcr7ZZv9PwtYvWSkOjgdZR2tJTc%3D",
                "assoc_animals": [
                    "African Elephant",
                    "Kangaroo"
                ], 
                "assoc_habitats": [
                    "Desert - Temperate",
                    "Desert - Hot"
                ]
            }

## All Threats [/all_threat_data]

### GET: /all_threat_names/ [GET]

Retrieves data for all threats.

This endpoint basically calls /single_threat_data on each threat.

**HTTP Request:**
`https://swe-endangered-animals.appspot.com/all_threat_names/`
    
+ Response 200 (application/json)

    + Body
    

            [
                {
                    "name": "Agro-industry farming",
                    "timing": "ongoing",
                    "severity":"3.57",
                    "image":"https://iucnredlist-photos.s3.amazonaws.com/thumb/1315258020.jpg?AWSAccessKeyId=AKIAJIJQNN2N2SMHLZJA&Expires=1536230105&Signature=Hcr7ZZv9PwtYvWSkOjgdZR2tJTc%3D",
                    "assoc_animals": [
                        "African Elephant",
                        "Kangaroo"
                    ], 
                    "assoc_habitats": [
                        "Desert - Temperate",
                        "Desert - Hot"
                    ]
                },
                {
                    "name": "Agro-industry farming",
                    "timing": "ongoing",
                    "severity":"3.57",
                    "image":"https://iucnredlist-photos.s3.amazonaws.com/thumb/1315258020.jpg?AWSAccessKeyId=AKIAJIJQNN2N2SMHLZJA&Expires=1536230105&Signature=Hcr7ZZv9PwtYvWSkOjgdZR2tJTc%3D",
                    "assoc_animals": [
                        "African Elephant",
                        "Kangaroo"
                    ], 
                    "assoc_habitats": [
                        "Desert - Temperate",
                        "Desert - Hot"
                    ]
                }
                ...
            ]

## Habitat [/single_habitat_data/{habitat_name}]

### GET: /single_habitat_data/HABITAT [GET]

Retrieves data for a given habitat: name, image, suitability, associated animals/threats.

Example: Let's say you want to find data on "Forest-Temperate."
    
**HTTP Request:**
`https://swe-endangered-animals.appspot.com/single_habitat_data/Forest-Temperate`

+ Response 200 (application/json)

    + Body
    
            {
                "name": "Forest - Temperate",
                "suitability_status": "suitable",
                "imageUrl": "https://www.polyworld.com.au/wp-content/uploads/2015/03/16000L-Poly-Pool1.jpg",
                "assoc_animals": [
                    "African Elephant",
                    "Kangaroo"
                ],
                "assoc_threats": [
                    "Housing and urban areas", 
                    "Droughts"
                 ]
            }

## All Habitats [/all_habitat_data]

### GET: /all_habitat_data/ [GET]

Retrieves data for all habitats.

This endpoint basically calls /single_habitat_data on each habitat.

**HTTP Request:**
`https://swe-endangered-animals.appspot.com/all_habitat_data/`

+ Response 200 (application/json)

    + Body
    
            [
                {
                    "name": "Forest - Temperate",
                    "suitability_status": "suitable",
                    "imageUrl": "https://www.polyworld.com.au/wp-content/uploads/2015/03/16000L-Poly-Pool1.jpg",
                    "assoc_animals": [
                        "African Elephant",
                        "Kangaroo"
                    ],
                    "assoc_threats": [
                        "Housing and urban areas", 
                        "Droughts"
                     ]
                },
                {
                    "name": "Forest - Temperate",
                    "suitability_status": "suitable",
                    "imageUrl": "https://www.polyworld.com.au/wp-content/uploads/2015/03/16000L-Poly-Pool1.jpg",
                    "assoc_animals": [
                        "African Elephant",
                        "Kangaroo"
                    ],
                    "assoc_threats": [
                        "Housing and urban areas", 
                        "Droughts"
                     ]
                }
                ...
            ]

## Country [/single_country_data/{country_name}]

### GET: /single_country_data/COUNTRY [GET]

Retrieves data for a specific country: name, flag, coordinates, associated animals/habitats.

Example: Let's say you want to find data on "Burundi."
    
**HTTP Request:**
`https://swe-endangered-animals.appspot.com/single_country_data/Burundi`

+ Response 200 (application/json)

    + Body
    
            {
                "name":"Burundi",
                "flag": "https://iucnredlist-photos.s3.amazonaws.com/thumb/1315258020.jpg?AWSAccessKeyId=AKIAJIJQNN2N2SMHLZJA&Expires=1536230105&Signature=Hcr7ZZv9PwtYvWSkOjgdZR2tJTc%3D",
                "coordinates": "lat: 28.033886 lng: 1.659626",
                "assoc_animals": [
                    "African Elephant",
                    "Kangaroo"
                ],
                "assoc_habitats": [
                    "Housing and urban areas",
                    "Droughts"
                ]
            }

## All Countries [/all_country_data]

### GET: /all_country_names [GET]

Retrieves data for all countries.
    
This endpoint basically calls /single_country_data on each country.

**HTTP Request:**
`https://swe-endangered-animals.appspot.com/all_country_names/`

+ Response 200 (application/json)

    + Body
    
            [
                {
                    "name":"Burundi",
                    "flag": "https://iucnredlist-photos.s3.amazonaws.com/thumb/1315258020.jpg?AWSAccessKeyId=AKIAJIJQNN2N2SMHLZJA&Expires=1536230105&Signature=Hcr7ZZv9PwtYvWSkOjgdZR2tJTc%3D",
                    "coordinates": "lat: 28.033886 lng: 1.659626",
                    "assoc_animals": [
                        "African Elephant",
                        "Kangaroo"
                    ],
                    "assoc_habitats": [
                        "Housing and urban areas",
                        "Droughts"
                    ]
                },
                {
                    "name":"Burundi",
                    "flag": "https://iucnredlist-photos.s3.amazonaws.com/thumb/1315258020.jpg?AWSAccessKeyId=AKIAJIJQNN2N2SMHLZJA&Expires=1536230105&Signature=Hcr7ZZv9PwtYvWSkOjgdZR2tJTc%3D",
                    "coordinates": "lat: 28.033886 lng: 1.659626",
                    "assoc_animals": [
                        "African Elephant",
                        "Kangaroo"
                    ],
                    "assoc_habitats": [
                        "Housing and urban areas",
                        "Droughts"
                    ]
                }
                ...
            ]
            